controller_list:
  - name: m1n6s200
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - m1n6s200_joint_1
      - m1n6s200_joint_2
      - m1n6s200_joint_3
      - m1n6s200_joint_4
      - m1n6s200_joint_5
      - m1n6s200_joint_6
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.2
      m1n6s200_joint_1:
        goal: 0.05
        trajectory: 0.5
      m1n6s200_joint_2:
        goal: 0.05
        trajectory: 0.5
      m1n6s200_joint_3:
        goal: 0.05
        trajectory: 0.5
      m1n6s200_joint_4:
        goal: 0.05
        trajectory: 0.5
      m1n6s200_joint_5:
        goal: 0.05
        trajectory: 0.5
      m1n6s200_joint_6:
        goal: 0.05
        trajectory: 0.5
  - name: m1n6s200_gripper
    action_ns: gripper_command
    type: GripperCommand
    default: true    
    joints:
      - m1n6s200_joint_finger_1
      - m1n6s200_joint_finger_2
