controller_list:
  - name: m1n6s200_arm_controller
    action_ns: m1n6s200/follow_joint_trajectory  # 添加命名空间前缀
    type: FollowJointTrajectory
    default: true
    joints:
      - m1n6s200_joint_1
      - m1n6s200_joint_2
      - m1n6s200_joint_3
      - m1n6s200_joint_4
      - m1n6s200_joint_5
      - m1n6s200_joint_6      
  - name: m1n6s200_gripper_controller
    action_ns: m1n6s200_gripper/gripper_command  # 使用对应的话题
    type: FollowJointTrajectory  # 类型建议统一
    default: true    
    joints:
      - m1n6s200_joint_finger_1
      - m1n6s200_joint_finger_2